### PR TITLE
Fix/cnch config file not found issue

### PR DESCRIPTION
**Pull request by weigangchen1**
Fix/cnch config file not found issue

### CODE REVIEW

**Review by dmthuc — APPROVED** [review]

**Comment by dmthuc** [comment]
fix #5 , #4

**Comment by dmthuc** [comment]
close #4, #5

**Comment by dmthuc** [comment]
fix #1

**Comment by FourSpaces** [comment]
@dmthuc   The issue has not been completely fixed. Although the cnch config.yaml file has been added, references need to be added to the resource manager. yaml, tso. yaml, worker. yaml, daemon manager. yaml, and server. yaml files, which should be written in the above file

```
cnch_ config: /etc/byconity/cnch-config.yaml
```

At the same time, it is necessary to clean up any duplicate configurations in the above configuration file and the cnch config.yaml file.

**Comment by WillemJiang** [comment]
@FourSpaces  Do you mind creating a PR with your proposed fix？

**Comment by FourSpaces** [comment]
I can submit a PR

**Pull request merged**
